### Configurations from config server
jwt-user:
  keys:
    access-token-key: '{"kty":"oct","k":"h4dfgRX5ZRZooHem3mEnctZ-KtR9FoESgCnH-3BNgde8"}'
#
redis-user:
  host: 192.168.0.125
  port: 6379
#
discovery-service-user:
  server:
    hostname: localhost
    port: 8010
  credentials:
    username: user
    password: pass
#
kafka-user:
  hostname: test
###

gateway:
  api-prefix: /api/v1k

spring:
  application:
    name: api-gateway
  profiles:
    active: discovery-service-user, jwt-user, redis-user
  config:
    import: optional:configserver:http://${CONFIG_SERVER_USER}:${CONFIG_SERVER_PASSWORD}@${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8012}

  data.redis:
    host: ${redis-user.host}
    port: ${redis-user.port}

  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      default-filters:
        - name: RequestRateLimiter
          args:
            rate-limiter: '#{@redisRateLimiter}'
            key-resolver: '#{@ipKeyResolver}'

server.port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://${discovery-service-user.server.hostname}:${discovery-service-user.server.port}/eureka
    register-with-eureka: false
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      access: unrestricted
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'